---
- hosts: siphon
  sudo: yes

  vars:
    - homeDir: /william/git
    - appDir: /siphon-ansible
    

  tasks:
  - name: Install Packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - build-essential
      - npm
      - curl
      - nodejs-legacy
      - git


